---

#- name: Install python-software-properties
#  yum: name=python-software-properties state=installed update_cache=yes

- name: Install python-pycurl
  yum: name=python-pycurl state=installed

- name: Import jenkins key
  rpm_key:
    key: '{{ jenkins_redhat_key }}'
    state: present
    validate_certs: no

- name: Get jenkins repo for ansible
  get_url:
    url: '{{ jenkins_redhat_repo }}'
    dest: /etc/yum.repos.d/jenkins.repo
