---
# Add Jenkins repository
- include: repo.yml

# Install dependencies
- include: dependencies.yml

# Install Jenkins
- name: Install Jenkins
  apt: pkg=jenkins state=latest update-cache=yes
  register: jenkins_install
  tags:
    - packages

# Install Jenkins cli
- include: cli.yml
