# Hard -restart Jenkins
- name: Hard Restart Jenkins
  sudo: yes
  service: name=jenkins state=restarted

# Safe-restart Jenkins
- name: Restart Jenkins
  sudo: yes
  command: java -jar {{ jenkins.cli_dest }} -s http://localhost:{{ port }} safe-restart